### ISSUE TITLE
Cannot update or create items in the wishlist!

### ISSUE THREAD

**Issue by migloh** [PhuongPhg/SAVABLE#26]
![image](https://user-images.githubusercontent.com/45881848/80335032-43eb3900-887d-11ea-9d90-151bd1db9e29.png)
After reorganizing the files, there is a error occured when I try to update or create a new item in the wishlist!

**Comment by PhuongPhg** [comment]
I think the problem is on the file in the webhost.
The problem is missing session part which is ``` session_start()``` . In the [savedata.php](https://github.com/PhuongPhg/SAVABLE/blob/master/php/savedata.php), the session still there.

And because the update items is 
```
mysqli_query($connect,"INSERT INTO wishlist (id, username, name, achieve, budget) VALUES($id, '$userr', '$namee', $achieve, $budget)");
```
which contain ```$userr=$_SESSION['username'] ``` while session is missing so it's cannot be update.
